//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pi5.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.DateTime> duracao { get; set; }
        public string descricao { get; set; }
        public Nullable<int> id_local { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual local local { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
