//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pi5.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class local
    {
        public local()
        {
            this.evento = new HashSet<evento>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<int> capacidade { get; set; }
        public string equipamentos { get; set; }
        public Nullable<int> id_unidade { get; set; }
    
        public virtual ICollection<evento> evento { get; set; }
        public virtual unidade unidade { get; set; }
    }
}
