//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pi5.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidade
    {
        public unidade()
        {
            this.local = new HashSet<local>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string endereco { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<local> local { get; set; }
    }
}
